In [1]:
import numpy as np

In [2]:
class Matrix:
    def __init__(self, matrix1, matrix2):
        self.matrix1 = np.array(matrix1).reshape(3,3)
        self.matrix2 = np.array(matrix2).reshape(3,3)

    def add_matrices(self):
        return self.matrix1 + self.matrix2

    def subtract_matrices(self):
        return self.matrix1 - self.matrix2

    def multiply_matrices(self):
        return np.dot(self.matrix1, self.matrix2)

matrix1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matrix2 = [[10, 11, 12], [13, 14, 15], [16, 17, 18]]

matrix = Matrix(matrix1, matrix2)

print(matrix.add_matrices())
print(matrix.subtract_matrices())
print(matrix.multiply_matrices())

[[11 13 15]
 [17 19 21]
 [23 25 27]]
[[-9 -9 -9]
 [-9 -9 -9]
 [-9 -9 -9]]
[[ 84  90  96]
 [201 216 231]
 [318 342 366]]


In [3]:
arr = np.arange(1, 10)

matrix = arr.reshape((3, 3))

print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
matrix = np.arange(1, 10).reshape(3, 3)

transposed_matrix = np.transpose(matrix)

print(transposed_matrix)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [5]:
matrix = np.arange(1, 10).reshape(3, 3)

result = matrix * 5

print(result)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [6]:
horizontal_matrix = np.array([[1, 2, 3]])

vertical_matrix = np.array([[4], [5], [6]])

print(horizontal_matrix)
print(vertical_matrix)

[[1 2 3]]
[[4]
 [5]
 [6]]


In [7]:
horizontal_matrix = np.array([[1, 2, 3]])

vertical_matrix = np.array([[4], [5], [6]])

result = np.dot(horizontal_matrix, vertical_matrix)

print(result)

[[32]]
